# Generated by Django 2.0.5 on 2018-05-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180515_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assigned_users',
        ),
        migrations.AddField(
            model_name='column',
            name='tasks',
            field=models.ManyToManyField(to='project.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Task'),
        ),
    ]
