# Generated by Django 2.0.5 on 2018-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180517_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
