# Generated by Django 2.0.5 on 2018-05-18 04:00

from django.db import migrations
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180518_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='column_order',
            field=lib.models.ListField(),
        ),
        migrations.AlterField(
            model_name='column',
            name='task_order',
            field=lib.models.ListField(),
        ),
    ]
